# GOOGLE_CLIENT_ID: 894679142333-b46aicon9ueo644sfe30f8eq9shoi5l1.apps.googleusercontent.com
# GOOGLE_CLIENT_SECRET: Ea8FTm5_mVowzQ1WpjWafut-
GOOGLE_API_KEY: AIzaSyDgZ2gt4VrbBqXR9gSQdWgVg4EPZVFQB2M
GOOGLE_CLIENT_ID: 1020920580951-7vi59bf4dlp7qb9m6t6qcq5jgckv0714.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: IPNL80SpBgZ42TgciWGaJlJl
