# PostgreSQL. Versions 8.2 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
local: &local
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USER'] %>
  template: template0

heroku: &heroku
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["HEROKU_DATABASE"] %> 
  username: <%= ENV["HEROKU_USERNAME"] %> 
  password: <%= ENV["HEROKU_PASSWORD"] %> 
  host: <%= ENV["HEROKU_HOST"] %> 
  port: <%= ENV["HEROKU_PORT"] %> 

development:
  <<: *local
  database: <%= Rails.application.class.parent_name %>_development

test:
  <<: *local
  database: <%= Rails.application.class.parent_name %>_test

production:
  <<: *heroku
#  database: <%= Rails.application.class.parent_name %>_production

prices:
  <<: *heroku



